version: "3.7"
services:
  nginx:
    image: 452573839730.dkr.ecr.us-east-1.amazonaws.com/enigma-nginx:https
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: 452573839730.dkr.ecr.us-east-1.amazonaws.com/enigma-backend:https
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"

volumes:
  static_volume: {}
